---
- hosts: repo-servers
  become: true
  gather_facts: yes
  name: install and configure repo server
  roles:
  # preparing server and hardening
    - { role: roles/preparing_server, become: True, tags: preparing_server }
  # install and configure docker service
    - { role: roles/docker, become: True, tags: docker_setup }