global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.zoho.eu:587'
  smtp_from: 'notification@mecan.ir'
  smtp_auth_username: 'notification@mecan.ir'
  smtp_auth_password: 'Yvmq9sEud1sPAZGclZG5RUsflAQYgZ'
  smtp_auth_identity: 'notification@mecan.ir'

route:
  receiver: 'Production_Environment'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  group_by: ['instance', 'severity']

receivers:
- name: 'Production_Environment'
  telegram_configs:
  - bot_token: '21212154dsad'
    api_url: "https://api.telegram.org"
    chat_id: -100000
    parse_mode: ""
    send_resolved: true
    disable_notifications: false
  # - http_configs:
  #      proxy_url: 'http://test.mecan.ir:8123'
  #     follow_redirects: true
  #     enable_http2: true
  email_configs:
    - send_resolved: true
      to: 'daneshfarabbas@gmail.com'