global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
      monitor: prom

rule_files:
  - /etc/prometheus/alerts/*.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'cadvisor-private'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'node-exporter-private'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  - job_name: 'cadvisor-public'
    static_configs:
      - targets:
        - "172.16.20.151:8080"
        - "172.16.20.149:8080"
        - "172.16.20.150:8080"
        - "172.16.20.146:8080"
        - "172.16.20.152:8080"
    scheme: "http"
    basic_auth:
      username: 'mecan'
      password: 'L3Wkwcufc3xhsE5eomtoUaKTLRIdV0'

  - job_name: 'node-exporter-public'
    static_configs:
      - targets:
        - "172.16.20.151:9100"
        - "172.16.20.149:9100"
        - "172.16.20.150:9100"
        - "172.16.20.146:8080"
        - "172.16.20.152:8080"
    scheme: "http"
    basic_auth:
      username: 'mecan'
      password: 'L3Wkwcufc3xhsE5eomtoUaKTLRIdV0'

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']

  - job_name: 'blackbox-ping'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets:
          - 8.8.8.8
          - google.com
          - node-exporter
          - blackbox-exporter
          - cadvisor
          - pushgateway
          - alertmanager
          - grafana
          - prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'alertmanager'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'pushgateway'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8082']
  
  - job_name: 'gitlab-ci-pipelines-exporter'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['gitlab-ci-pipelines-exporter:8080']

  - job_name: gitlab-redis
    static_configs:
      - targets:
        - 172.16.20.152:9121
    scheme: "http"
    basic_auth:
      username: 'mecan'
      password: 'L3Wkwcufc3xhsE5eomtoUaKTLRIdV0'




  - job_name: gitlab-postgres
    static_configs:
      - targets:
        - 172.16.20.152:9187
    scheme: "http"
    basic_auth:
      username: 'mecan'
      password: 'L3Wkwcufc3xhsE5eomtoUaKTLRIdV0'


  - job_name: gitlab_exporter_database
    metrics_path: "/database"
    static_configs:
      - targets:
        - 172.16.20.152:9168
    scheme: "http"
    basic_auth:
      username: 'mecan'
      password: 'L3Wkwcufc3xhsE5eomtoUaKTLRIdV0'

    
  - job_name: gitlab_exporter_sidekiq
    metrics_path: "/sidekiq"
    static_configs:
      - targets:
        - 172.16.20.152:9168
    scheme: "http"
    basic_auth:
      username: 'mecan'
      password: 'L3Wkwcufc3xhsE5eomtoUaKTLRIdV0'
